In [3]:
with open('smartphone.html','r',encoding='utf-8') as f:
    html = f.read()

In [4]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in g:\data science\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in g:\data science\lib\site-packages (from beautifulsoup4) (2.3.1)

In [20]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [13]:
soup= BeautifulSoup(html,'lxml')

In [16]:
container=soup.find_all('div',{'class':'sm-product has-tag has-features has-actions'})

In [24]:
name = []
price= []
specs =[]

for i in container:
    name.append(i.find('h2').text)
    price.append(i.find('span',{'class':'price'}).text)
    try:
         specs.append(i.find('div',{'class':'score rank-2-bg'}).find('b').text)
    except:
         specs.append(np.nan)

In [25]:
len(name)

1020

In [28]:
df = pd.DataFrame({
    'Model':name,
    'Price':price,
    'Rating:':specs
})

In [29]:
df

                            Model      Price Rating:
0                    Oppo Reno 8T    ₹29,999      86
1                   OnePlus 11 5G    ₹56,999      89
2       OnePlus Nord CE 2 Lite 5G    ₹18,999      81
3                     OnePlus 11R    ₹39,999      85
4     Samsung Galaxy S23 Ultra 5G  ₹1,24,999     NaN
...                           ...        ...     ...
1015                 Karbonn K531     ₹1,299     NaN
1016                       TMB T3     ₹1,349     NaN
1017                Peace Mi3 Pro       ₹799     NaN
1018                Cellecor A40i     ₹1,449     NaN
1019                Micromax X413       ₹832     NaN

[1020 rows x 3 columns]

In [30]:
names = []
prices = []
ratings = []
sim = []
processor = []
ram = []
battery = []
display = []
camera = []
card = []
os = []

for i in soup.find_all('div',{'class':'sm-product has-tag has-features has-actions'}):
    try:
        names.append(i.find('h2').text)
    except:
        names.append(np.nan)
    try:
        prices.append(i.find('span',{'class':'price'}).text)
    except:
        price.append(np.nan)
    try:
        ratings.append(i.find('div',{'class':'score rank-2-bg'}).find('b').text)
    except:
        ratings.append(np.nan)
        
    x = i.find('ul',{'class':'sm-feat specs'}).find_all('li')
    try:
        sim.append(x[0].text)
    except:
        sim.append(np.nan)
    try:
        processor.append(x[1].text)
    except:
        processor.append(np.nan)
    try:    
        ram.append(x[2].text)
    except:
        ram.append(np.nan)
    try:
        battery.append(x[3].text)
    except:
        battery.append(np.nan)
    try:
        display.append(x[4].text)
    except:
        display.append(np.nan)
    try:
        camera.append(x[5].text)
    except:
        camera.append(np.nan)
    try:
        card.append(x[6].text)
    except:
        card.append(np.nan)
    try:
        os.append(x[7].text)
    except:
        os.append(np.nan)

In [31]:
len(name)

1020

In [32]:
len(price)

1020

In [33]:
len(specs)

1020

In [34]:
df = pd.DataFrame({
    'model':names,
    'price':prices,
    'rating':ratings,
    'sim':sim,
    'processor':processor,
    'ram':ram,
    'battery':battery,
    'display':display,
    'camera':camera,
    'card':card,
    'os':os
})

In [35]:
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,Oppo Reno 8T,"₹29,999",86,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 2 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v13
1,OnePlus 11 5G,"₹56,999",89,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
2,OnePlus Nord CE 2 Lite 5G,"₹18,999",81,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
3,OnePlus 11R,"₹39,999",85,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.74 inches, 1240 x 2772 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
4,Samsung Galaxy S23 Ultra 5G,"₹1,24,999",NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.8 inches, 1440 x 3088 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Karbonn K531,"₹1,299",NaN,Dual Sim,No Wifi,1 MHz Processor,"32 MB RAM, 32 MB inbuilt",1750 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 16 GB"
1016,TMB T3,"₹1,349",NaN,Dual Sim,"32 MB RAM, 64 MB inbuilt",1050 mAh Battery,"1.8 inches, 240 x 320 px Display",1.3 MP Rear Camera,Bluetooth,NaN,NaN
1017,Peace Mi3 Pro,₹799,NaN,Dual Sim,"64 MB RAM, 128 MB inbuilt",2500 mAh Battery,"2 inches, 320 x 240 px Display",0.3 MP Rear Camera,NaN,NaN,NaN
1018,Cellecor A40i,"₹1,449",NaN,Dual Sim,1.5 MHz Processor,"32 MB RAM, 32 MB inbuilt",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.8 MP Rear Camera,"Memory Card Supported, upto 32 GB",No FM Radio
1019,Micromax X413,₹832,NaN,Dual Sim,1 MHz Processor,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",0.3 MP Rear Camera,No FM Radio,NaN

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     714 non-null    object
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1009 non-null   object
 9   card       972 non-null    object
 10  os         905 non-null    object
dtypes: object(11)
memory usage: 87.8+ KB